import type {Metadata} from "next";
import {Bricolage_Grotesque} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/generic/Navbar";
import CursorFollower from "@/components/generic/CursorFollower";
import Footer from "@/components/generic/Footer";

const bricolageGrotesque = Bricolage_Grotesque({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout(
    {
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>) {
    return (
        <html lang="en" className={'dark'}>
        <body className={`${bricolageGrotesque.className} antialiased`}>
        <CursorFollower/>
        <Navbar/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}
